// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgcuydgyvcocdkyfvpqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnY3V5ZGd5dmNvY2RreWZ2cHF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3ODg4NDcsImV4cCI6MjA2MzM2NDg0N30.FmEne_KXuRlTPJyjoljy4hw4YuLx91DRaxRp9vgZifg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);